# Generated by Django 3.2 on 2021-05-21 22:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0003_auto_20210520_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='open_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 21, 22, 12, 40, 336291, tzinfo=utc)),
        ),
    ]
